export const games = [
    {
        name: 'Call of Duty: Modern Warfare',
        img: 'https://hb.imgix.net/d9ffbcf4aa5df29167b21484b9aac12507a9deb9.jpg?auto=compress,format&fit=crop&h=353&w=616&s=523a92154bf15e96dc83c5c113f93bcf',
        id: 1,
        genre: 'Shooter',
    },
    {
        name: 'Call of Duty: Warzone',
        img: 'https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/blog/hero/mw-wz/WZ-Season-Three-Announce-TOUT.jpg',
        id: 2,
        genre: 'Shooter',
    },
    {
        name: 'Fortnite',
        img: 'https://cdn2.unrealengine.com/14br-consoles-1920x1080-wlogo-1920x1080-432974386.jpg',
        id: 3,
        genre: 'Shooter',
    },
    {
        name: 'Fifa 21',
        img: 'https://images.daznservices.com/di/library/GOAL/ca/f3/fifa-21-kylian-mbappe_5y8kt6rcv8tf1kifrjd2ku44c.jpg?t=2054301555&quality=100',
        id: 4,
        genre: 'Sport',
    },
    {
        name: 'NBA 2K21',
        img: 'https://cdn1.dotesports.com/wp-content/uploads/2020/07/01093935/Zion.jpg',
        id: 5,
        genre: 'Sport',
    },
    {
        name: 'PGA Tour 2k21',
        img: 'https://www.golfchannel.com/sites/default/files/2020/05/14/PGA%20TOUR%202K21%20Key%20Art%201920x1080.jpg',
        id: 6,
        genre: 'Sport',
    },
    {
        name: 'Rocket League',
        img: 'https://www.gamespot.com/a/uploads/screen_kubrick/1574/15746725/3734562-123.jpg',
        id: 7,
        genre: 'Sport',
    },
    {
        name: 'UFC 4',
        img: 'https://sirusgaming.com/wp-content/uploads/2020/07/ea-sports-ufc-4-01.jpg',
        id: 8,
        genre: 'Sport',
    },
    {
        name: 'Minecraft',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtWpcQ15hiAMmjW3f9_5xpiW1WrWG2LFHNCJYvik_JQObqmTmIGLnH65Nv0VGLDcpoARE&usqp=CAU',
        id: 9,
        genre: 'OpenWorld',
    },
    {
        name: 'GTA 5',
        img: 'https://images.pushsquare.com/83e694ebefd4e/grand-theft-auto-v-ps4-ps3-playstation-4-sales.original.jpg',
        id: 10,
        genre: 'OpenWorld',
    },
    {
        name: 'Assassin\'s Creed Valhalla',
        img: 'https://i.ytimg.com/vi/cEWNYwdRT-Q/maxresdefault.jpg',
        id: 11,
        genre: 'OpenWorld',
    },
    {
        name: 'Red Dead Redemption 2',
        img: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/capsule_616x353.jpg?t=1618851907',
        id: 12,
        genre: 'OpenWorld',
    },
    {
        name: 'Roblox',
        img: 'https://sharkapk.com/storage/appsCover/com.roblox.client/roblox-apk-cover.jpg',
        id: 13,
        genre: 'OpenWorld',
    },
    {
        name: 'Terraria',
        img: 'https://savesforgames.com/wp-content/uploads/2016/05/terraria-1.jpg',
        id: 14,
        genre: 'OpenWorld',
    },
    {
        name: 'Rust',
        img: 'https://images2.minutemediacdn.com/image/upload/c_fill,w_720,ar_16:9,f_auto,q_auto,g_auto/shape/cover/sport/dataimagejpegbase649j4AAQSkZJRgABAQAAAQABAAD4Sg0RX-fcb2d7f067d5706e2a6d340c29bbbee9.jpg',
        id: 15,
        genre: 'OpenWorld',
    },
    {
        name: 'Ark',
        img: 'https://i.ytimg.com/vi/f6F0EAsYBFg/maxresdefault.jpg',
        id: 16,
        genre: 'OpenWorld',
    },
    {
        name: 'Mario Kart 8 Deluxe',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTIE_74E6uQigOh19E24Knf8XdzxOFl4ebnb5-YCwIfZRN5HQspZuUsUtwlzsQc8_9eYs&usqp=CAU',
        id: 17,
        genre: 'Racing',
    },
    {
        name: 'F1 2021',
        img: 'https://i.ytimg.com/vi/QNCA0DpvV7Q/maxresdefault.jpg',
        id: 18,
        genre: 'Racing',
    },
    {
        name: 'Forza Horizon 4',
        img: 'https://i.ytimg.com/vi/eoB-8nKS348/maxresdefault.jpg',
        id: 19,
        genre: 'Racing',
    },
    {
        name: 'Riders Republic',
        img: 'https://staticctf.akamaized.net/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUQTn/2xPC6PFDjTRlggOCjIpUc2/4ad5850b47c21a6520f456230b827461/Riders-Republic-Pack-Art.jpg',
        id: 20,
        genre: 'Racing',
    },
    {
        name: 'Apex Legends',
        img: 'https://cdn.wccftech.com/wp-content/uploads/2019/02/apex-legends-keyart.jpg',
        id: 21,
        genre: 'Shooter',
    },
    {
        name: 'Valorant',
        img: 'https://www.mobygames.com/images/covers/l/663244-valorant-windows-front-cover.jpg',
        id: 22,
        genre: 'Shooter',
    },
    {
        name: 'CS:GO',
        img: 'https://www.techadvisor.com/cmsdata/features/3645914/counter_strike_global_offensive_thumb800.jpg',
        id: 23,
        genre: 'Shooter',
    },
    {
        name: 'Overwatch',
        img: 'https://www.mobygames.com/images/covers/l/340276-overwatch-origins-edition-windows-front-cover.jpg',
        id: 31,
        genre: 'Shooter',
    },
    {
        name: 'Super Smash Bros Ultimate',
        img: 'https://www.smashbros.com/assets_v2/img/sns/en.png?180613',
        id: 24,
        genre: 'Fighter',
    },
    {
        name: 'Street Fighter V',
        img: 'https://sfgalleries.net/art/sf5/sf5/sfv-poster1_big.jpg',
        id: 25,
        genre: 'Fighter',
    },
    {
        name: 'Tekken 7',
        img: 'https://ougaming.com/images/news/large/182-ougt7cover.jpg',
        id: 26,
        genre: 'Fighter',
    },
    {
        name: 'Mortal Kombat 11',
        img: 'https://d1lss44hh2trtw.cloudfront.net/assets/article/2020/10/08/mortal-kombat-11-will-upgrade-to-ps5-xbox-series-for-free-with-cross-gen-play_feature.jpg',
        id: 27,
        genre: 'Fighter',
    },
    {
        name: 'League of Legends',
        img: 'https://cdn.arstechnica.net/wp-content/uploads/2015/02/lol.png',
        id: 28,
        genre: 'MOBA',
    },
    {
        name: 'Dota 2',
        img: 'https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota2_social.jpg',
        id: 29,
        genre: 'MOBA',
    },
    {
        name: 'Pokemon Unite',
        img: 'https://e.snmc.io/lk/lv/x/b590f85c552d8d6323fbf2c5316514f9/9180370',
        id: 30,
        genre: 'MOBA',
    },
];